name: Create Daily Release Branch

# active after test
on:
  push:
    branches: [ "*" ]
  # schedule:
  #   - cron: '0 16 * * 0-4'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.MY_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Set daily branch name
        id: set_branch_name
        run: |
          BRANCH_NAME="release-$(date --date 'tomorrow' +%Y-%m-%d)"
          echo "::set-output name=branch_name::$BRANCH_NAME"

      - name: Git Setting
        run: |
          git config --global user.email "deliyami@gmail.com"
          git config --global user.name "Ci Schedule Bot"

      - name: Create release branch and pr
        run: |
          
          gh pr create --base main --head test2 --title "Pull Request 제목" --body "Pull Request 설명"

# gh pr create -B main -t ${{ steps.set_branch_name.outputs.branch_name }} -b "" -H ${{ steps.set_branch_name.outputs.branch_name }}
