name: Create Daily Release Branch

# active after test
on:
  push:
    branches: [ "*" ]
  # schedule:
  #   - cron: '0 16 * * 0-4'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.MY_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Set daily branch name
        id: set_branch_name
        run: |
          BRANCH_NAME="release-$(date --date 'tomorrow' +%Y-%m-%d)"
          echo "::set-output name=branch_name::$BRANCH_NAME"

      - name: Git Setting
        run: |
          git config --global user.email "deliyami@gmail.com"
          git config --global user.name "Ci Schedule Bot"
          git remote set-url origin "https://${{ steps.set_branch_name.outputs.branch_name }}@github.com/deliyamiOrganizer/hello.git"

      - name: Create release branch and pr
        run: |
          git fetch origin main
          git checkout -b ${{ steps.set_branch_name.outputs.branch_name }} origin/main
          git push -o merge_request.create -o merge_request.target=main -o merge_request.title="${{ steps.set_branch_name.outputs.branch_name }}" origin ${{ steps.set_branch_name.outputs.branch_name }}
