name: Close Daily Release Branch

# active after test
on:
  schedule:
    - cron: '20 6 * * *' 

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Set daily branch name
        id: set_branch_name
        run: |
          BRANCH_NAME="release/$(date --date 'tomorrow' +%Y-%m-%d)"
          # BRANCH_NAME="release-$(date --date 'today' +%Y-%m-%d)"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Git Setting
        run: |
          git config --global user.email "deliyami@gmail.com"
          git config --global user.name "Ci Schedule Bot"
          git remote set-url origin "https://github.com/deliyamiOrganizer/hello.git"

      - name: Create release branch and pr
        run: |
          git fetch origin ${{ $BRANCH_NAME }}
          # git checkout -b ${{ $BRANCH_NAME }}
          git push -d origin ${{ $BRANCH_NAME }}
