name: Create Daily Release Branch

# active after test
on:
  schedule:
    - cron: '35 6 * * *'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Set daily branch name
        id: set_branch_name
        run: |
          BRANCH_NAME="release/$(date --date 'tomorrow' +%Y-%m-%d)"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Git Setting
        run: |
          git config --global user.email "deliyami@gmail.com"
          git config --global user.name "Ci Schedule Bot"
          # git remote set-url origin "https://${{ $BRANCH_NAME }}@github.com/deliyamiOrganizer/hello.git"
          # git remote set-url origin "https://github.com/deliyamiOrganizer/hello.git"

      - name: Create release branch and pr
        run: |
          git fetch origin main
          git checkout -b ${{ $BRANCH_NAME }} origin/main
          git commit --allow-empty -m "Release/${{ $BRANCH_NAME }}"
          git push origin ${{ $BRANCH_NAME }}
          gh pr create -B main -t ${{ $BRANCH_NAME }} -b ${{ $BRANCH_NAME }}
